version: '3.7'

services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: yuridefranca/nodejs:1.0.0
    working_dir: /var/www/html
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    tty: true
    env_file:
      - ./.env
    ports:
      - ${DOCKER_APP_PORT}:${APP_PORT}
    volumes:
      - ./code/:/var/www/html
